### ISSUE TITLE
How to change Title?

### ISSUE THREAD

**Issue by felix-schindler** [VIkill33/SwiftUI-ContributionChart#6]
Maybe I'm just stupid, but I can't seem to find a way to change the Title. When adding it to the View constructor

```swift
ContributionChartView(
    data: data!,
    rows: 4,
    columns: 14,
    targetValue: 5,
    blockColor: .green,
    valueText: "Another title"
)
```

Xcode gives me the error: `Extra argument 'valueText' in call`

https://github.com/VIkill33/SwiftUI-ContributionChart/blob/a7ba6f6e57fb1220cd7305d7f17078903bc8760f/Sources/ContributionChart/ContributionChartView.swift#L17

**Comment by VIkill33** [comment]
My bad, valueText ain't do nothing here, maybe I forgot to delete that from code. But ContributionChartView doesn't take valueText as a parameter, so just remove it when you call this View.
For example, you could add a title in this way:
```
VStack {
        Text("Title here")
        ContributionChartView(
                data: data!,
                rows: 4,
                columns: 14,
                targetValue: 5,
                blockColor: .green
        )
}
```

**Comment by felix-schindler** [comment]
You've actually fixed this in https://github.com/VIkill33/SwiftUI-ContributionChart/commit/8590318aa3ab2f307a656b7d60d87b0569f225a3

However, your last release (version 1.0.1) was the commit before.
